### PR TITLE
Fix Email Generation

### LINKED ISSUE #196: Preview/Test doesn't show Firstname/Surname etc
Should autoreplace with either a random name or the 'firstname' etc.

### PR DESCRIPTION
**Pull request by Meatballs1**
* Fixes a bug introduced in fdd6b2e4a84fa07b347e4018579c061fe29c629c. @target no longer available for email generation
* Ensures Victim email addresses are unique for a campaign (Are there unintended consequences to this?)
* If generating a dummy victim the mailer now places in values for the names. 

Fixes #196

### CODE REVIEW

File: app/models/victim.rb [hunk 1]
```diff
@@ -3,6 +3,7 @@ class Victim < ActiveRecord::Base
 	has_many :visits, dependent: :destroy
 
 	validates_format_of :email_address, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
+  validates_uniqueness_of :email_address, scope: :campaign_id
```
Comment (zeknox) [inline app/models/victim.rb]: indent issue

Comment (Meatballs1) [inline app/models/victim.rb]: Theres currently a mixture of indent types in the codebase. ><

Comment (zeknox) [inline app/models/victim.rb]: yeah tell me about it! 2 space soft tabs is my pref

**Comment by Meatballs1** [comment]
N.b. I probably need to work more on checking rspecs are working :)

File: app/models/campaign.rb [hunk 2]
```diff
@@ -103,63 +107,53 @@ def test_victim
...
-      if entry.scan(/,/).count == 0
-        # email
-        parse_single_csv
-      elsif entry.scan(/,/).count == 1
-        # firstname, email
-        parse_double_csv
-      elsif entry.scan(/,/).count == 2
-        # firstname, lastname, email
-        parse_triple_csv
+  def validate_email_addresses
```
Comment (zeknox) [inline app/models/campaign.rb]: I think this method is being a bit restrictive... I'm unable to add any targets on this branch.

Comment (Meatballs1) [inline app/models/campaign.rb]: On which errors?

Comment (Meatballs1) [inline app/models/campaign.rb]: N.b. unless you are getting error messages it will be because the validation in Victim isn't unique...

Comment (zeknox) [inline app/models/campaign.rb]: Yeah, my bad, had a git snafu going on where I overlapped some branches... all good here.
